### PR TITLE
Depend on stable flutter instead of master

### LINKED ISSUE #29: Project in a broken state
Flutter 1.23.0-8.0.pre.137 • channel master • https://github.com/flutter/flutter.git
Framework • revision ece2f98eb0
Engine • revision a8d7d97bef
Tools • Dart 2.11.0 (build 2.11.0-185.0.dev)

Lots of errors in the project in the starter branch

Several instance where these errors occurs:
`Undefined name 'standardEasing'`
`Undefined name 'Router'.`
`The method 'ChildBackButtonDispatcher' isn't defined for the type '_MailRouter'. `
`The name 'RootBackButtonDispatcher' isn't a type, so it can't be used in an 'as' expression.`
`The method 'Router' isn't defined for the type '_MailRouter'.`
`Mixin can only be applied to class.`
`Classes can only mix in mixins and classes.`
`Classes can only extend other classes.`
`Undefined class 'RouteInformation'.`
`The method 'RouteInformation' isn't defined for the type 'ReplyRouteInformationParser'.`

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change fixes #29 

Navigator 2.0 has been merged into the stable branch of Flutter and landed with version 1.22 this month, but the `TransitionBuilderPage` (used to build pages with custom transitions) has been removed from master (https://github.com/flutter/flutter/pull/66694). Issue #29 points out that the build is broken. To reduce build breakages we should depend on stable. This change includes any overhead for the `starter` branch to depend on stable. 

The main changes are that instead of our SharedAxis and FadeThrough transition page wrappers extending `TransitionBuilderPage`, they now extend `Page` and the implementation has been updated to reflect this.

Code snippets in instructions should be updated to reflect new code. Instructions to be on master branch at the beginning of the codelab can also be removed/replaced with stable branch.

### CODE REVIEW

File: lib/router.dart [hunk 1]
```diff
@@ -96,29 +96,30 @@ class ReplySearchPath extends ReplyRoutePath {
   const ReplySearchPath();
 }
 
-class SharedAxisTransitionPageWrapper extends TransitionBuilderPage {
-  SharedAxisTransitionPageWrapper(
+class SharedAxisTransitionPageWrapper extends Page {
```
Comment (guidezpl) [inline lib/router.dart:99]: maybe add a similar TODO as in #30

**Review by guidezpl — APPROVED** [review]
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

**Review by perclasson — APPROVED** [review]
LGTM

File: lib/mail_view_router.dart [hunk 2]
```diff
@@ -97,27 +97,28 @@ class MailViewRouterDelegate extends RouterDelegate<void>
   }
 }
 
-class FadeThroughTransitionPageWrapper extends TransitionBuilderPage {
+class FadeThroughTransitionPageWrapper extends Page {
```
Comment (perclasson) [inline lib/mail_view_router.dart:100]: Thanks for doing this update Renzo!

I changed the codelab now to:
1. Remove instruction to use master branch
2. Updated `lib/mail_view_router.dart` and `lib/router.dart` in codelab
3. Updated code snippet for `FadeThroughTransitionPageWrapper`
4. Updated code snippet for `SharedAxisTransitionPageWrapper`
5. Added const to `router.dart`

Does it look good? Just published the changes.

**Review by perclasson — APPROVED** [review]

File: lib/router.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply lib/router.dart:99]: done.

File: lib/mail_view_router.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply lib/mail_view_router.dart:102]: Happy to do it :)

Looks good to me with a few changes.

1. CustomTransitionBuilderPage -> CustomTransitionPage
2. I just updated `SharedAxisTransitionPageWrapper` and `FadeThroughTransitionPageWrapper` to use `transitionsBuilder` parameter. 
3. Under `SharedAxisTransitionPageWrapper` there is a green box that mentions `TransitionBuilderPage`, that mention should be removed.

File: lib/router.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply lib/router.dart:101]: Added.

File: lib/mail_view_router.dart (hunk 2 above)
Comment (perclasson) [reply lib/mail_view_router.dart:102]: Cool!  :) I changed that now, hopefully I got it right.

Comment (Renzo-Olivares) [reply lib/mail_view_router.dart:102]: Awesome! Sorry I think I missed these. 

On page 7 and 8 there is a mention of `TransitionBuilderPage` that can be changed to `CustomTransitionPage`. 

The code snippets on page 4 and 7  `CustomTransitionBuilderPage` -> `CustomTransitionPage`.

Everything else looks good.

Thanks Per!

Comment (perclasson) [reply lib/mail_view_router.dart:102]: Updated! 🎉

Comment (Renzo-Olivares) [reply lib/mail_view_router.dart:102]: Looks good! Both PR's should be good to go.
