### PR TITLE
Depend on stable flutter instead of master

### LINKED ISSUE #29: Project in a broken state
Flutter 1.23.0-8.0.pre.137 • channel master • https://github.com/flutter/flutter.git
Framework • revision ece2f98eb0
Engine • revision a8d7d97bef
Tools • Dart 2.11.0 (build 2.11.0-185.0.dev)

Lots of errors in the project in the starter branch

Several instance where these errors occurs:
`Undefined name 'standardEasing'`
`Undefined name 'Router'.`
`The method 'ChildBackButtonDispatcher' isn't defined for the type '_MailRouter'. `
`The name 'RootBackButtonDispatcher' isn't a type, so it can't be used in an 'as' expression.`
`The method 'Router' isn't defined for the type '_MailRouter'.`
`Mixin can only be applied to class.`
`Classes can only mix in mixins and classes.`
`Classes can only extend other classes.`
`Undefined class 'RouteInformation'.`
`The method 'RouteInformation' isn't defined for the type 'ReplyRouteInformationParser'.`

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change fixes #29 

Navigator 2.0 has been merged into the stable branch of Flutter and landed with version 1.22 this month, but the `TransitionBuilderPage` (used to build pages with custom transitions) has not landed on stable. Issue #29 points out that the build is broken. To reduce build breakages we should depend on stable. This change includes any overhead for the `starter` branch to depend on stable. 

This change implements a `CustomTransitionBuilderPage`, as a temporary solution for `TransitionBuilderPage` not being on stable. 

Code snippets in instructions should be updated to reflect new code. Instructions to be on master branch at the beginning of the codelab can also be removed/replaced with stable branch.

### CODE REVIEW

**Comment by Renzo-Olivares** [comment]
@googlebot I signed it!

File: lib/transition_page_builder.dart [hunk 1]
```diff
@@ -0,0 +1,22 @@
+import 'package:flutter/widgets.dart';
+
+// Prefer to use TransitionBuilderPage once it lands in stable.
```
Comment (guidezpl) [inline lib/transition_page_builder.dart:3]: can you add a TODO with an issue link?

File: lib/transition_page_builder.dart [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+class CustomTransitionPageBuilder extends Page {
+  final Widget screen;
+  final ValueKey transitionKey;
+
+  const CustomTransitionPageBuilder(
+      {@required this.screen, @required this.transitionKey})
```
Comment (guidezpl) [inline lib/transition_page_builder.dart:9]: nit: formatting

**Review by guidezpl — APPROVED** [review]
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

**Review by perclasson — APPROVED** [review]
LGTM

File: lib/transition_page_builder.dart [hunk 3]
```diff
@@ -0,0 +1,22 @@
+import 'package:flutter/widgets.dart';
+
+// Prefer to use TransitionBuilderPage once it lands in stable.
+class CustomTransitionPageBuilder extends Page {
```
Comment (clocksmith) [inline lib/transition_page_builder.dart:4]: nit: rename to CustomTransitionPage since this really isn't a builder

**Review by clocksmith — APPROVED** [review]

File: lib/transition_page_builder.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply lib/transition_page_builder.dart]: Done!
